<?php

namespace Sandikodev\LaravelZodTransformer\Commands;

use Illuminate\Console\Command;
use Sandikodev\LaravelZodTransformer\Collectors\FormRequestCollector;
use Sandikodev\LaravelZodTransformer\Generators\ValibotSchemaGenerator;
use Sandikodev\LaravelZodTransformer\Generators\ZodSchemaGenerator;
use Sandikodev\LaravelZodTransformer\Parsers\LaravelRuleParser;

class GenerateZodSchemasCommand extends Command
{
    protected $signature = 'zod:generate 
                            {--driver= : Target validator driver (zod, valibot)}
                            {--coerce : Enable automatic type coercion (z.coerce)}
                            {--path=* : Custom paths to scan for FormRequests}
                            {--output= : Custom output file path}
                            {--dry-run : Print generated TypeScript to stdout without writing to file}';

    protected $description = 'Transform Laravel FormRequests into clean, type-safe Zod/Valibot schemas';

    public function handle(): int
    {
        $startTime = microtime(true);

        $driver = strtolower((string) ($this->option('driver') ?: config('zod-transformer.driver', 'zod')));
        $coerce = (bool) ($this->option('coerce') ?: config('zod-transformer.coerce', false));
        $paths = (array) ($this->option('path') ?: config('zod-transformer.paths', [app_path('Http/Requests')]));
        $outputFile = (string) ($this->option('output') ?: config('zod-transformer.output_file', resource_path('js/schemas/generated.zod.ts')));
        $ignorePatterns = (array) config('zod-transformer.ignore', []);
        $generateInferredTypes = (bool) config('zod-transformer.generate_inferred_types', true);

        $this->components->info(sprintf('Scanning FormRequests for [%s] schema generation...', strtoupper($driver)));

        $collector = new FormRequestCollector();
        $collectedRequests = $collector->collect($paths, $ignorePatterns);

        if (empty($collectedRequests)) {
            $this->components->warn('No FormRequests found in configured paths.');
            return self::SUCCESS;
        }

        $parser = new LaravelRuleParser();
        $generator = match ($driver) {
            'valibot' => new ValibotSchemaGenerator(),
            default => new ZodSchemaGenerator(),
        };

        $sections = [];
        $sections[] = '// Auto-generated by @sandikodev/laravel-zod-transformer';
        $sections[] = '// Do not edit this file directly. Changes will be overwritten.';
        $sections[] = '// Generated at: ' . date('Y-m-d H:i:s T');
        $sections[] = '';

        if ($driver === 'valibot') {
            $sections[] = 'import * as v from "valibot";';
        } else {
            $sections[] = 'import { z } from "zod";';
        }
        $sections[] = '';

        $schemaCount = 0;

        foreach ($collectedRequests as $item) {
            $rules = $item['rules'];
            $messages = $item['messages'];
            $schemaName = $item['schemaName'];
            $className = $item['class'];

            $fieldDefinitions = $parser->parse($rules, $messages);
            $schemaCode = $generator->generate($schemaName, $fieldDefinitions, [
                'generate_inferred_types' => $generateInferredTypes,
                'coerce' => $coerce,
            ]);

            $sections[] = sprintf('// ─── %s (%s) ───', $schemaName, class_basename($className));
            $sections[] = $schemaCode;
            $sections[] = '';

            $schemaCount++;
            $this->components->twoColumnDetail($schemaName, sprintf('<fg=gray>%s</>', class_basename($className)));
        }

        $fullContent = implode("\n", $sections) . "\n";

        if ($this->option('dry-run')) {
            $this->line($fullContent);
            return self::SUCCESS;
        }

        $outputDir = dirname($outputFile);
        if (!is_dir($outputDir)) {
            mkdir($outputDir, 0755, true);
        }

        file_put_contents($outputFile, $fullContent);

        $elapsed = round((microtime(true) - $startTime) * 1000, 2);

        $this->newLine();
        $this->components->info(sprintf(
            'Successfully generated %d %s %s to [%s] in %sms',
            $schemaCount,
            strtoupper($driver),
            $schemaCount === 1 ? 'schema' : 'schemas',
            $outputFile,
            $elapsed
        ));

        return self::SUCCESS;
    }
}
